name: Telecom Data Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root     # Password for MySQL service in GitHub Actions
          MYSQL_DATABASE: telecom_db    # Database name for CI
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cryptography  # Fixes missing dependency for SHA256 auth

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -proot --silent; then
              echo "MySQL is ready!"
              break
            fi
            sleep 2
          done

      - name: Run Telecom Pipeline
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DB: telecom_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root   # ✅ Matches the MySQL service password in CI
        run: |
          echo "Starting Telecom Data Pipeline..."
          python src/pipeline.py
