name: Run Telecom Data Pipeline

on:
  schedule:
    - cron: "0 8 * * *"  # runs daily at 8 AM UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: telecom_db
          MYSQL_USER: telecom_user
          MYSQL_PASSWORD: telecom_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cryptography

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -u telecom_user -ptelecom_pass -e "SELECT 1" telecom_db &> /dev/null; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Still waiting..."
            sleep 2
          done

      - name: Run Telecom Pipeline
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DB: telecom_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Mysql#10
        run: |
          python src/pipeline.py
